### ISSUE TITLE
Depositors can be powered by redstone repeaters

### ISSUE THREAD

**Issue by tobi-blackscale** [IThundxr/CreateNumismatics#30]
This allows triggering the connected mechanism without paying.
![grafik](https://github.com/Layers-of-Railways/CreateNumismatics/assets/71216944/3008a383-d042-499c-bc92-9f945979fb3b)

**Comment by VladisCrafter** [comment]
I'm pretty much sure it doesn't activate it - the pulse of repeater just goes through the depositor. This is what they can fix tho.

**Comment by tobi-blackscale** [comment]
Not sure what you mean by "activate"...
It's not generating money, if that was the concern.

**Comment by VladisCrafter** [comment]
Depositor does generate a redstone signal when given required coins, right? Well, it also does pass a redstone signal through itself, so the output can be activated by another signal, hence without paying anything.

**Comment by winnetrie83** [comment]
@VladisCrafter 
It is highly unlikely this could ever be a problem. For as be on a server, the server has very likely a claim/chunk protection, where (other)players will not be able to trigger a redstone signal in any other way.
If this is on a unprotected server, then there is also a chance players just mine trough the blocks instead of paying.

In other words: If players can bypass the pay gate they can also just mine the block.
Can't see the issue here.

**Comment by tobi-blackscale** [comment]
You are not wrong, but this still looks like unintended behavior and could also happen by accident in tight spaces. 

So if it can be fixed, it should be fixed.

**Comment by winnetrie83** [comment]
As far as i know that is normal vanilla behaviour. It is up to the player to build correctly. 
There are blocks in vanilla that doesn't let redstone signals trough, i think glass.

**Comment by VladisCrafter** [comment]
...and the depositor blocks can also behave like that! That's probably the solution to *this exact* problem. Right, @winnetrie83?

**Comment by winnetrie83** [comment]
Yes ofcourse i believe so, BUT.....
It might interfere with the redstone functionality. Just like any other redstone block like pistons and droppers etc etc. They all let redstone signals trough.
So maybe the developers can fix this, but there is a chance it just can't be fixed, because of the vanilla code.
